language: generic

services:
  - docker

env:
  - REGISTRY: registry.gitlab.com/tc211/geodetic-registry-docker/web

jobs:
  include:
    - stage: build
      script: bash .travis/docker_build.sh
    - stage: push
      script: bash .travis/docker_push.sh
