language: generic

services:
  - docker

env:
  - DOCKER_REGISTRY: tc211/geodetic-registry-docker/web
  - DOCKER_TAG: ${DOCKER_REGISTRY}:travis-${TRAVIS_BUILD_NUMBER}

before_install:
  - bash .travis/docker_build.sh

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: travis