language: generic

services:
  - docker

env:
  global:
    - CI_REGISTRY: registry.gitlab.com
    - CI_REGISTRY_IMAGE: ${CI_REGISTRY}/tc211/geodetic-registry-docker/web:t${TRAVIS_BUILD_NUMBER}

before_install:
  - bash .travis/docker_build.sh

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: travis