language: generic

services:
  - docker

env:
  - REGISTRY: registry.gitlab.com/tc211/geodetic-registry-docker/web

before_install:
  - bash .travis/docker_build.sh

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: travis