#! /bin/bash

PROFILES=$@

if [ -z $@ ]; then
    PROFILESARG=""
else
    PROFILESARG="-P ${PROFILES}"
fi

mkdir -p dist
rm dist/*

set -e

# update current branch

git pull origin 

# update submodule

#cd registry-base
#git fetch origin
#cd ..
git submodule update --recursive

# compile
mvn -Dmaven.test.skip=true -Dproject.build.sourceEncoding=UTF-8 ${PROFILESARG} clean compile package
cp iso-registry-client/target/*.war dist

