version: '3'

#findepi/graalvm

services:
  db:
    image: postgres:12.8
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=isoreg"
      - "POSTGRES_PASSWORD=isoreg"
      - "POSTGRES_DB=isoreg"
    networks:
      - main

#  tc8:
#    build:
#      dockerfile: Dockerfile-dev
#      context: .
#    ports:
#      - "8080:80"
#    depends_on:
#      - db
#    networks:
#      - main

networks:
  main:
