#! /bin/bash

PROFILES=$@

if [ -z $@ ]; then
    PROFILESARG=""
else
    PROFILESARG="-P ${PROFILES}"
fi

# update current branch

git pull origin 

# update submodule

#cd registry-base
#git pull origin
#cd ..
git submodule update --recursive

# migrate
mvn -Dmaven.test.skip=true ${PROFILESARG} flyway:migrate

