ALTER TABLE concatenatedoperationitem_coordinateoperationitem RENAME COLUMN coordoperation_uuid TO coordinateoperations_uuid;
ALTER TABLE concatenatedoperationitem_coordinateoperationitem_aud RENAME COLUMN coordoperation_uuid TO coordinateoperations_uuid;

ALTER TABLE concatenatedoperationitem_coordinateoperationitem RENAME TO concatenatedoperationitem_singleoperationitem;
ALTER TABLE concatenatedoperationitem_coordinateoperationitem_aud RENAME TO concatenatedoperationitem_singleoperationitem_aud;