AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: REGIONAL

Resources:
    PetStoreFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: org.iso.registry.client.StreamLambdaHandler::handleRequest
            Runtime: java8
            CodeUri: target/isoreg-lambda.zip
            MemorySize: 1512
            Policies: AWSLambdaBasicExecutionRole
            Timeout: 60
            Events:
                GetResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    IsoRegistryApi:
        Description: URL for application
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/isoreg'
        Export:
            Name: IsoRegistryApi
