name: Publish Docker

# only for branch docker
on: {push: {branches: [docker]}}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 50
    - uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        registry: docker.pkg.github.com
        name: iso-tc211/iso-geodetic-registry/iso-registry
#        name: ${{github.repository}}/iso-registry
        username: ${{github.actor}}
        password: ${{github.token}}
#        //:owner/:repo_name/:image_name.