name: Publish Docker

on: {push: {branches: [gaction]}}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build-tag-publish docker images
      env:
        CI_REGISTRY: "docker.pkg.github.com"
        CI_REGISTRY_IMAGE: "${{github.repository}}"
        DOCKER_LOGIN_USERNAME: "${{github.actor}}"
        DOCKER_LOGIN_PASSWORD: "${{github.token}}"
      run: |
        bash .github-sh/docker_build.sh
        bash .github-sh/docker_push.sh
        echo "DONE !!!"