name: on-release

on:
  release:
    types: [ published ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 50

      - uses: olegtarasov/get-tag@v2

      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          dockerfile: Dockerfile
          tags: "latest,${{env.GIT_TAG_NAME}}"
          registry: docker.pkg.github.com
          name: ${{env.REPOSITORY_NAME}}/webapp-aws
          username: ${{github.actor}}
          password: ${{env.GITHUB_TOKEN}}
