name: docker

on:
  push:
    branches:
      - 'releases/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 50
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        registry: docker.pkg.github.com
        name: ${{github.repository}}/iso-registry
        username: ${{github.actor}}
        password: ${{github.token}}
#        //:owner/:repo_name/:image_name.