name: Test pull request

on:  [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 50
    - name: exec docker to test build
      run: |
        docker build .